name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install pnpm@latest -g

      - name: Install Dependencies
        run: pnpm install

      - name: Run Checks
        run: pnpm run check

      - name: Run Build
        run: pnpm run build

      - name: Run Tests
        run: pnpm run test:build
